version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: rechord
          RAILS_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: rechord
          POSTGRES_DB: rechord_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/rechord

    steps:
      - checkout

      # bundle
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - rails-demo-bundle-v3-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rails-demo-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # yarn
      - restore_cache:
          keys:
            - rails-demo-yarn-v2-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-v2-
      - run:
          name: yarn install
          command: curl -o- -L https://yarnpkg.com/install.sh; yarn install
      - save_cache:
          key: rails-demo-yarn-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # database
      - run:
          name: Database setup
          command: |
            bin/rails db:create
            bin/rails db:structure:load

      # test
      - run:
          name: check lint
          command: yarn lint
      - run:
          name: jest
          command: yarn test
