version: '3'
services:
  db:
    image: postgres:10.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
    volumes:
      - ./.localdocker/postgres/data:/var/lib/postgresql/data
