default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:  5000
  database: <%= ENV['RAILS_DATABASE'] %>
  host:     <%= ENV['RAILS_DATABASE_HOST'] %>
  port:     <%= ENV['RAILS_DATABASE_PORT'] %>
  username: <%= ENV['RAILS_DATABASE_USERNAME'] %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  database: <%= ENV['RAILS_DATABASE_TEST'] %>
